#!/usr/bin/php
<?php

// Inspired by posts here http://www.domoticaforum.eu/viewtopic.php?f=66&t=6654

$host = getenv('max_elv_host');
$port = getenv('max_elv_port');
$hostname = (getenv('max_elv_hostname') ? getenv('max_elv_hostname') : null);
$metar = getenv('max_elv_metar');

if (isset($hostname)) {
    echo "host_name " . $hostname . "\n";
}

$fp = @fsockopen($host, $port, $errno, $errstr, 5);
if (!$fp) {
    die("ERROR CONNECTING ($errno, $errstr)\n");
}

socket_set_blocking($fp,false);

$buffer = "";
while (!feof($fp)) {
    $line = fgets($fp);
    
    if ($line != "")
        $buffer .= $line."\n";
    if (strpos($line,"L:") !== false)
            break;
}
fclose($fp);

$array = explode("\n\n",$buffer);

$metar_file = file_get_contents("http://weather.noaa.gov/pub/data/observations/metar/stations/" . $metar . ".TXT");
$metar_array = explode("\n", $metar_file);

if (preg_match("/^EKYT [0-9]{6}Z [0-9]{3}([0-9]{2})KT .* ([0-9]{2})\/[0-9]{2} .*$/", $metar_array[1], $matches)) {
  $metar_wind = $matches[1];
  $metar_temp = $matches[2];
} else {
  $metar_wind = 0;
  $metar_temp = 0;
}

$data = array();

foreach ($array as $element) {
    $type = substr($element, 0,1);

    switch ($type) {
    case 'M':
        parse_M(substr($element, 8), $data);
        break;
    case 'L':
        parse_L(substr($element, 2), $data);
        break;
    }
}

function parse_M ($raw, &$data) {
    $temp = base64_decode($raw);

    $num = bin2hex(substr($temp, 2, 1));

    $temp = substr($temp, 3);

    while(strlen($temp) > 0 && $num-- > 0) {
        $length = ord(substr($temp, 1, 1));
        $name = substr($temp, 1+1, $length);
        $id = bin2hex(substr($temp, 1+1+$length,3));

        $data[$id]['name'] = $name;
        
        $temp = substr($temp, 1+1+$length+3);
    }
}

function parse_L ($raw, &$data) {
    $temp =  base64_decode($raw);

    while (strlen($temp) > 0) {
        $length = ord(substr($temp, 0, 1));
        
        $id = bin2hex(substr($temp, 1, 3));
        $valve = ord(substr($temp, 7, 1));
        $temperature = (ord(substr($temp, 8, 1))/2);

        $data[$id]['valve'] = $valve;
        $data[$id]['temp'] = $temperature;
        
        $temp = substr($temp, $length+1);
    }
}

foreach ($data as $id => $d) {
    echo "multigraph " . $id . "\n";
    if (array_key_exists(1, $argv) && $argv[1] === 'config') {
        echo "graph_title MAX ELV - " . $d['name'] . "\n";
        echo "graph_category HomeAutomation" . "\n";
        echo "temp.label C° setpoint\n";
        echo "metar_temp.label C° outside\n";
        echo "metar_wind.label wind in kt\n";
        echo "valve.label valve % opened\n";
	echo "temp.draw AREA\n";
	echo "metar_temp.draw LINE2\n";
	echo "metar_wind.draw LINE2\n";
	echo "valve.draw LINE2\n";
	echo "temp.colour FFFF00\n";
	echo "metar_temp.colour 00FF00\n";
	echo "metar_wind.colour FF0000\n";
	echo "valve.colour 000000\n";
    } else {
        echo "temp.value " . $d['temp'] . "\n";
        echo "metar_temp.value " . $metar_temp . "\n";
        echo "metar_wind.value " . $metar_wind . "\n";
        echo "valve.value " . $d['valve'] . "\n";
    }
    echo "\n";
}
